# fly.toml app configuration file generated for svjewels on 2026-06-09T05:18:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'svjewels'
primary_region = 'lax'

[build]

[env]
  DATA_DIR = '/data'
  NODE_ENV = 'production'
  PORT = '3000'

[[mounts]]
  source = 'sv_jewels_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '5s'
    method = 'GET'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
